"""MockAIProvider — deterministic, offline candidate generation.

Used for demos, tests and development without a DeepSeek API key
(``AI_PROVIDER=mock``). Produces valid candidates from transcript windows so
the full pipeline (validation → timestamp correction → scoring → UI) can be
exercised end-to-end. Never used in production by default.
"""

from __future__ import annotations

import structlog

from app.providers.base import AIProvider

logger = structlog.get_logger(__name__)


class MockAIProvider(AIProvider):
    def __init__(self, max_clips: int | None = None) -> None:
        self._max_clips = max_clips or 5

    # ------------------------------------------------------------------ utils

    @staticmethod
    def _window_text(segments: list[dict]) -> str:
        return " ".join(seg.get("text", "") for seg in segments).strip()

    def _build_windows(
        self, segments: list[dict], duration: float, min_dur: float = 18.0, max_dur: float = 55.0
    ) -> list[tuple[float, float, str]]:
        windows: list[tuple[float, float, str]] = []
        current: list[dict] = []
        window_start: float | None = None

        for seg in segments:
            if window_start is None:
                window_start = seg["start"]
            current.append(seg)
            window_end = seg["end"]
            window_dur = window_end - window_start

            if window_dur >= min_dur or window_end >= duration - 0.5:
                if len(windows) < self._max_clips:
                    windows.append((window_start, window_end, self._window_text(current)))
                current = []
                window_start = None

        # Video shorter than min_dur — one window covering everything.
        if not windows and segments:
            windows.append(
                (
                    segments[0]["start"],
                    segments[-1]["end"],
                    self._window_text(segments),
                )
            )
        return windows

    # ------------------------------------------------------------- interface

    def analyze_transcript(self, transcript: dict) -> dict:
        segments = transcript.get("segments", [])
        duration = transcript.get("duration") or (segments[-1]["end"] if segments else 0.0)

        windows = self._build_windows(segments, float(duration))
        clips: list[dict] = []
        for index, (start, end, text) in enumerate(windows):
            words = text.split()
            title = " ".join(words[:6]) if words else f"Clip {index + 1}"
            hook = " ".join(words[:12]) if words else ""
            # Deterministic sub-scores; the analysis service computes the
            # §19 overall score from these.
            clips.append(
                {
                    "start_time": round(start, 3),
                    "end_time": round(end, 3),
                    "title": title,
                    "hook": hook,
                    "reason": "Mock heuristic: deterministic transcript window.",
                    "hook_score": 78,
                    "content_score": 84,
                    "context_score": 76,
                    "emotion_score": 68,
                    "standalone_score": 86,
                    "retention_score": 80,
                }
            )

        logger.info("mock_analysis_generated", clips=len(clips), windows=len(windows))
        return {"clips": clips}

    def rank_clips(self, clips: list[dict]) -> list[dict]:
        return sorted(clips, key=lambda c: c.get("score", 0), reverse=True)

    def generate_metadata(self, clip: dict) -> dict:
        return {
            "title": clip.get("title", "Clip"),
            "description": "Auto-generated by ClipForge (mock AI).",
            "hashtags": ["#shorts", "#clipforge"],
            "tags": ["shorts"],
        }

    def generate_hook(self, clip: dict) -> str:
        return (clip.get("hook") or clip.get("title") or "Watch this")[:60]
